name: flutter_cubit_project
description: Use Cubit Project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.4.0
  flutter_bloc: ^8.1.2
  freezed: ^2.4.3
  dio: ^4.0.4
  retrofit: ^3.3.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.1
  go_router: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
